### ISSUE TITLE
TLDS resonators KLayout script does not work

### ISSUE THREAD

**Issue by PetervandenDoel** [SiEPIC/UBC-ELEC413-2024#1]
We followed the instructions on the GitHub we downloaded all the right packages and we're trying to run the TLDS resonators script in Klayout. When Both Travis and I run it we get the exact same error. Please help us

![image](https://github.com/SiEPIC/UBC-ELEC413-2024/assets/73015873/3b51be26-3c86-4efc-8d16-b33ae0cc2f93)

**Comment by lukasc-ubc** [comment]
Did you install the ZEP PDK?
