### ISSUE TITLE
Cannot create my own KLayout script copying the student one code

### ISSUE THREAD

**Issue by PetervandenDoel** [SiEPIC/UBC-ELEC413-2024#2]
When I try to create my own design, def design_Peter, that copies of code from the student one design with the function properly named  I get this issue. Travis gets the exact same issue as well 

![image](https://github.com/SiEPIC/UBC-ELEC413-2024/assets/73015873/674b004b-228b-41b6-aecc-e03af6b10dcc)

**Comment by lukasc-ubc** [comment]
Can you please attach your scripts here, and someone else can try to run it on their installation?

**Comment by lukasc-ubc** [comment]
Please use KLayout 0.28.12.  It seems like there is a bug in 0.28.15
